sudo: required
services:
  - docker

before_install:
  - docker build -t johnlorac/docker-react -f Dockerfile.dev .

script:
  - docker run johnlorac/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-eu-central-1-103099220287"
  bucket-path: "docker-react"
  on:
    branch: master
